stages:
  - test

variables:
  NODE_ENV: test

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.0-jammy
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
    reports:
      junit: playwright-report/results.xml